In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

loc = 'E:\data\Football-Hackathon-Sevilla-FC'

In [2]:
data = pd.read_csv(loc + '\\train.csv')
test = pd.read_csv(loc + '\\test.csv')
sub  = pd.read_csv(loc + '\\sample_submission_wBWLI0s.csv')

In [3]:
data

,row_id,scout_id,rating_num,winner,team,competitionId,player_position_1,player_position_2,player_height,player_weight,...,team2_defensive_derived_var_10,team2_offensive_derived_var_11,team2_offensive_derived_var_12,team2_offensive_derived_var_13,team2_offensive_derived_var_14,team2_defensive_derived_var_15,team2_offensive_derived_var_16,team2_defensive_derived_var_17,team2_offensive_derived_var_18,team2_offensive_derived_var_19
0,1,13,7.0,winner,team1,8,7.0,7.0,0.317073,0.48,...,0.193658,0.131548,0.097131,0.600944,0.338892,0.347980,0.034157,0.288962,0.310727,0.204925
1,3,16,6.5,loser,team2,8,3.0,9.0,0.463415,0.42,...,0.190500,0.173697,0.272801,0.605659,0.526761,0.468976,0.054034,0.334962,0.380073,0.295392
2,4,4,8.5,loser,team1,5,11.0,11.0,0.682927,0.44,...,0.312314,0.250756,0.212631,0.558833,0.686523,0.441749,0.219441,0.414288,0.570757,0.437500
3,5,13,8.0,loser,team2,4,17.0,17.0,0.682927,0.58,...,0.282556,0.155969,0.206503,0.533002,0.373959,0.527733,0.095201,0.423040,0.330754,0.235558
4,7,11,3.5,draw,team1,5,10.0,10.0,0.731707,0.70,...,0.450453,0.199050,0.134002,0.688773,0.681724,0.733625,0.128719,0.448360,0.444946,0.312500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20448,29221,14,5.0,draw,team2,14,NaN,NaN,0.439024,0.26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20449,29223,3,6.0,winner,team2,11,4.0,4.0,0.390244,0.32,...,0.362193,0.240326,0.369752,0.438649,0.381099,0.264074,0.171927,0.422975,0.588501,0.534694
20450,29224,4,5.0,loser,team1,7,5.0,5.0,0.268293,0.30,...,0.341322,0.248870,0.240096,0.515025,0.694587,0.869000,0.296820,0.511550,0.548315,0.385927
20451,29226,13,6.0,loser,team1,8,5.0,5.0,0.463415,0.46,...,0.215831,0.190395,0.207007,0.631279,0.330606,0.322158,0.108018,0.333229,0.349177,0.458685
20452,29227,4,6.0,winner,team2,4,4.0,4.0,0.585366,0.36,...,0.404569,0.229025,0.138451,0.746928,0.512851,0.544212,0.086429,0.446098,0.347572,0.329782

In [6]:
abc = data.groupby('winner')['rating_num'].mean().to_dict()

In [7]:
abc

{'draw': 6.904094010614101,
 'loser': 6.431232536479354,
 'winner': 7.213508872352604}

In [8]:
test['rating_num'] = test['winner'].map(abc)

In [9]:
sub['rating_num'] = test['rating_num']

In [10]:
sub.to_csv('mean_01.csv', index = False)

In [11]:
sub

      row_id  rating_num
0      14785    6.904094
1      15125    6.904094
2      13095    6.431233
3       6079    6.431233
4      16584    7.213509
...      ...         ...
8769   21259    6.431233
8770    9371    6.904094
8771   23226    6.431233
8772   26623    7.213509
8773   13814    7.213509

[8774 rows x 2 columns]